channels:
- conda-forge
dependencies:
- python=3.13.1
- pip<=24.3.1
- pip:
  - mlflow==3.1.4
  - numpy==2.3.2
  - pandas==2.3.1
  - pyarrow==20.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.1
  - xgboost==3.0.2
name: mlflow-env
